version: '3.8'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - fretec-network
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fretec-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 12
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    networks:
      - fretec-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 12
  gateway:
    image: fretec/gateway:latest
    hostname: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      LOGIN_URI: http://login:8081
      CLIENT_URI: http://cliente:8082
      ORDER_URI: http://pedido:8083
    networks:
      - fretec-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
  login:
    image: fretec/login:latest
    hostname: login
    container_name: login
#    ports:
#      - "8081:8081"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/fatec
    networks:
      - fretec-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
  cliente:
    image: fretec/cliente:latest
    hostname: cliente
    container_name: cliente
#    ports:
#      - "8082:8082"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      MONGODB_URI: mongodb://mongodb:27017/fatec
    networks:
      - fretec-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
  pedido:
    image: fretec/pedido:latest
    hostname: pedido
    container_name: pedido
#    ports:
#      - "8083:8083"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      MONGODB_URI: mongodb://mongodb:27017/fatec
    networks:
      - fretec-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
          condition: service_started
      redis:
          condition: service_started

networks:
  fretec-network:
    driver: bridge