version: '3.8'

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - "TZ=America/Sao_Paulo"
    ports:
      - "27017:27017"
    networks:
      - fretec-network
  opensearch:
    image: opensearchproject/opensearch:2.4.0
    hostname: opensearch
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: on-failure
    networks:
      - fretec-network
  graylog:
    image: graylog/graylog:5.1.5
    hostname: graylog
    container_name: graylog
    depends_on:
      - mongo
      - opensearch
    environment:
      GRAYLOG_PASSWORD_SECRET: "f62c92ac283e4f1f969ad5e71d4c7b2e11e9bdbf5e193ae7bb4e9b4e1e956e437c98a43cd624c5ea8a2c97b9463f96e8"
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongo:27017/graylog"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    restart: on-failure
    networks:
      - fretec-network
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fretec-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 12
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    networks:
      - fretec-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 12
  gateway:
    image: fretec/gateway:latest
    hostname: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      LOGIN_URI: http://login:8081
      CLIENT_URI: http://cliente:8082
      ORDER_URI: http://pedido:8083
    networks:
      - fretec-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
      redis:
        condition: service_started
  login:
    image: fretec/login:latest
    hostname: login
    container_name: login
#    ports:
#      - "8081:8081"
    environment:
      MONGODB_URI: mongodb://mongo:27017/fatec
    networks:
      - fretec-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
      redis:
        condition: service_started
  cliente:
    image: fretec/cliente:latest
    hostname: cliente
    container_name: cliente
#    ports:
#      - "8082:8082"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      MONGODB_URI: mongodb://mongo:27017/fatec
    networks:
      - fretec-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
      redis:
        condition: service_started
  pedido:
    image: fretec/pedido:latest
    hostname: pedido
    container_name: pedido
#    ports:
#      - "8083:8083"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MONGODB_URI: mongodb://mongo:27017/fatec
    networks:
      - fretec-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
          condition: service_started
      redis:
          condition: service_started

networks:
  fretec-network:
    driver: bridge